---
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: donbowman/skaffold-flask
    context: .
    sync:
      '*.py': .
      'static': static
      'templates': templates
deploy:
  kubectl:
    manifests:
    - k8s.yaml
